; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
projects[drupal][version] = "8.0.0-dev"

; Modules
projects[devel][version] = "1.x-dev"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[dash][download][type] = ""
projects[dash][download][url] = ""
projects[dash][type] = "module"

