; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
projects[drupal][version] = "8.0.x"

; Modules
projects[devel][version] = "1.x-dev"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[tas_dash][download][type] = ""
;projects[tas_dash][download][url] = ""
;projects[tas_dash][type] = "module"

projects[tas_dash][download][type] = "git"
projects[tas_dash][download][url] = "https://github.com/LightMinder/tas_dash"
projects[tas_dash][type] = "module"

