; This file was auto-generated by drush make
api = 2
core = 7.x

; Core
projects[drupal][version] = "7.x"

; Modules
projects[wsclient][subdir] = "contrib"

projects[entity][subdir] = "contrib"
projects[devel][subdir] = "contrib"
projects[admin_menu][subdir] = "contrib"
projects[rules][subdir] = "contrib"
projects[http_client][subdir] = "contrib"
projects[oauth][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[link][subdir] = "contrib"
projects[encrypt][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[views][subdir] = "contrib"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[tas_dash][download][type] = ""
;projects[tas_dash][download][url] = ""
;projects[tas_dash][type] = "module"

projects[open_framework][download][type] = "git"
projects[open_framework][download][url] = "https://github.com/SU-SWS/open_framework.git"
projects[open_framework][type] = "theme"


projects[dash][download][type] = "git"
projects[dash][download][url] = "https://github.com/cjwest/dash.git"
projects[dash][type] = "module"
projects[dash][subdir] = "custom"