; This file was auto-generated by drush make
api = 2
core = 8.x

; Core
projects[drupal][version] = "8.0.0-beta6"

; Modules
projects[restui][subdir] = "contrib"

projects[devel][version] = "1.x-dev"
projects[devel][subdir] = "contrib"

projects[config_inspector][version] = "1.0-alpha2"
projects[config_inspector][subdir] = "contrib"

projects[config_tools][version] = "1.0-alpha3"
projects[config_tools][subdir] = "contrib"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[tas_dash][download][type] = ""
;projects[tas_dash][download][url] = ""
;projects[tas_dash][type] = "module"

projects[demo][download][type] = "git"
projects[demo][download][url] = "https://github.com/cjwest/demo.git"
projects[demo][type] = "module"
projects[demo][subdir] = "custom"

projects[dash][download][type] = "git"
projects[dash][download][url] = "https://github.com/cjwest/dash.git"
projects[dash][type] = "module"
projects[dash][subdir] = "custom"

