; This file was auto-generated by drush make
api = 2
core = 7.x

; Core
projects[drupal][version] = "7.x"

; Modules
projects[entity][subdir] = "contrib"
projects[devel][subdir] = "contrib"
projects[admin_menu][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[link][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[features][subdir] = "contrib"
; projects[bean][subdir] = "contrib"
; projects[ds][subdir] = "contrib"
; projects[email][subdir] = "contrib"
; projects[insert][subdir] = "contrib"
; projects[field_collection][subdir] = "contrib"
; projects[field_group][subdir] = "contrib"
; projects[site_map][subdir] = "contrib"
; projects[xmlsitemap][subdir] = "contrib"
projects[devel][subdir] = "contrib"
projects[css_injector][subdir] = "contrib"
projects[context][subdir] = "contrib"
projects[block_class][subdir] = "contrib"
projects[advanced_help][subdir] = "contrib"
projects[date][subdir] = "contrib"
projects[google_analytics][subdir] = "contrib"
projects[menu_block][subdir] = "contrib"
projects[menu_position][subdir] = "contrib"
projects[mollom][subdir] = "contrib"
projects[metatag][subdir] = "contrib"
projects[pathologic][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[redirect][subdir] = "contrib"
projects[strongarm][subdir] = "contrib"
projects[backup_migrate][subdir] = "contrib"
projects[diff][subdir] = "contrib"
projects[auto_nodetitle][subdir] = "contrib"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

projects[open_framework][download][type] = "git"
projects[open_framework][download][url] = "https://github.com/SU-SWS/open_framework.git"
projects[open_framework][type] = "theme"

projects[stanford_seven][download][type] = "git"
projects[stanford_seven][download][url] = "https://github.com/SU-SWS/stanford_seven.git"
projects[stanford_seven][type] = "theme"

projects[stanford_page][download][type] = "git"
projects[stanford_page][download][url] = "https://github.com/SU-SWS/stanford_page.git"
projects[stanford_page][type] = "module"

projects[stanford_bean_types][download][type] = "git"
projects[stanford_bean_types][download][url] = "https://github.com/SU-SWS/stanford_bean_types.git"
projects[stanford_bean_types][type] = "module"

projects[stanford_image][download][type] = "git"
projects[stanford_image][download][url] = "https://github.com/SU-SWS/stanford_image.git"
projects[stanford_image][type] = "module"

projects[stanford_image_styles][download][type] = "git"
projects[stanford_image_styles][download][url] = "https://github.com/SU-SWS/stanford_image_styles.git"
projects[stanford_image_styles][type] = "module"

projects[stanford_landing_page][download][type] = "git"
projects[stanford_landing_page][download][url] = "https://github.com/SU-SWS/stanford_landing_page.git"
projects[stanford_landing_page][type] = "module"

projects[stanford_landing_page][download][type] = "git"
projects[stanford_landing_page][download][url] = "https://github.com/SU-SWS/stanford_easy_wysiwyg_css.git"
projects[stanford_landing_page][type] = "module"

projects[stanford_landing_page][download][type] = "git"
projects[stanford_landing_page][download][url] = "https://github.com/SU-SWS/stanford_wysiwyg.git"
projects[stanford_landing_page][type] = "module"

