; This file was auto-generated by drush make
api = 2
core = 8.x

; Core
projects[drupal][version] = "8.0.0-beta4"

; Modules
projects[devel][version] = "1.x-dev"
projects[devel][subdir] = "contrib"

projects[restui][version] = "1.x-dev"
projects[restui][subdir] = "contrib"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[tas_dash][download][type] = ""
;projects[tas_dash][download][url] = ""
;projects[tas_dash][type] = "module"

projects[tas_dash][download][type] = "git"
projects[tas_dash][download][url] = "https://github.com/LightMinder/tas_dash"
projects[tas_dash][type] = "module"
projects[tas_dash][subdir] = "tas"

